# tracing
CONFIG_TRACING=y
CONFIG_TRACING_CTF=y
CONFIG_TRACING_ASYNC=y
CONFIG_TRACING_BACKEND_UART=y
CONFIG_TRACING_HANDLE_HOST_CMD=y
CONFIG_TRACING_BUFFER_SIZE=4096

# Fix timer tick rate
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=800000000
# Todo- asynchronous tracing does not work with CTF tracing. Use synchronous tracing for now
CONFIG_TRACING_SYNC=y

# If you encounter tx_overflow() messages from tracing, you can set these configurations to n.
CONFIG_TRACING_ISR=n
CONFIG_TRACING_SYSCALL=n
CONFIG_TRACING_IDLE=n
CONFIG_TRACING_THREAD=n
CONFIG_TRACING_WORK=n
CONFIG_TRACING_SEMAPHORE=n
CONFIG_TRACING_MUTEX=n
CONFIG_TRACING_CONDVAR=n
CONFIG_TRACING_QUEUE=n
CONFIG_TRACING_FIFO=n
CONFIG_TRACING_LIFO=n
CONFIG_TRACING_STACK=n
CONFIG_TRACING_MESSAGE_QUEUE=n
CONFIG_TRACING_MAILBOX=n
CONFIG_TRACING_PIPE=n
CONFIG_TRACING_HEAP=n
CONFIG_TRACING_MEMORY_SLAB=n
CONFIG_TRACING_TIMER=n
CONFIG_TRACING_EVENT=n
CONFIG_TRACING_POLLING=n
CONFIG_TRACING_PM=n
CONFIG_TRACING_NET_SOCKETS=n
CONFIG_TRACING_NET_CORE=n
